export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const FETCH_MORE_USERS = 'FETCH_MORE_USERS';
export const SET_LOGIN = 'SET_LOGIN';
export const INCREMENT_PAGE = 'INCREMENT_PAGE';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
